name: Auto Label Team PR (Official GitHub Script) 🔒

on:
  # Déclenche le workflow lors de la création ou de la réouverture d'une Pull Request.
  pull_request:
    types: [opened, reopened]

env:
  # ➡️ 1. REMPLACEZ CECI : Le SLUG de votre équipe (ex: "dev-backend" ou "qa-team").
  TEAM_SLUG: "app-b2c"
  # ➡️ 2. Le nom du label à appliquer.
  PR_LABEL: "AppCore"

jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # ESSENTIEL pour ajouter le label.

    steps:
      - name: Check Team Membership and Apply Label
        # C'est l'action qui remplace l'action introuvable.
        uses: actions/github-script@v7 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Récupération des variables nécessaires
            const teamSlug = process.env.TEAM_SLUG;
            const prAuthor = context.payload.pull_request.user.login;
            const org = context.repo.owner;
            const prNumber = context.issue.number;
            const label = process.env.PR_LABEL;

            console.log(`Checking if user ${prAuthor} is a member of team ${org}/${teamSlug}...`);

            try {
              // 1. Appel à l'API GitHub pour vérifier l'appartenance à l'équipe.
              // Succès (statut 200) signifie que l'utilisateur est membre.
              await github.rest.teams.getMembershipForUserInOrg({
                org: org,
                team_slug: teamSlug,
                username: prAuthor,
              });

              console.log(`✅ User ${prAuthor} is a member! Applying label "${label}".`);

              // 2. Application du label
              await github.rest.issues.addLabels({
                owner: org,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: [label],
              });

              console.log(`Label "${label}" applied successfully.`);

            } catch (error) {
              // Si l'API retourne une erreur 404 (Not Found), l'utilisateur n'est PAS membre.
              if (error.status === 404) {
                console.log(`❌ User ${prAuthor} is NOT a team member. Skipping label.`);
              } 
              // Si c'est une autre erreur (ex: 403 Forbidden, problème de token), on signale l'échec.
              else {
                console.error(`An unexpected error occurred (Status: ${error.status}):`, error.message);
                // On lève une erreur pour faire échouer le job et alerter l'utilisateur.
                throw new Error(`Failed to check team membership. Check GITHUB_TOKEN permissions.`);
              }
            }
