name: Auto Label Team PR (by Team Membership)

on:
  pull_request:
    types: [opened, reopened]

env:
  # ➡️ 1. REMPLACEZ : Le SLUG de votre équipe (tout en minuscules, sans l'organisation).
  TEAM_SLUG: "app-b2c"
  # ➡️ 2. Le nom du label à appliquer.
  PR_LABEL: "AppCore"

jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Nécessaire pour ajouter un label.
      
    steps:
      - name: Checkout code
        # Nécessaire pour accéder au script JavaScript dans le dépôt
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Configure l'environnement Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (Octokit)
        # Installe la librairie Octokit nécessaire pour le script
        run: npm install @octokit/rest
      - name: Check team membership and apply label
        id: check_label
        # Exécute le script Node.js qui fera le travail
        run: node .github/workflows/check-team.js
        env:
          # Passe les variables nécessaires au script JS
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          ORGANIZATION: ${{ github.repository_owner }}
          TEAM_SLUG: ${{ env.TEAM_SLUG }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_LABEL: ${{ env.PR_LABEL }}
